fos_user_group_list:
    pattern: /liste
    defaults : { _controller :FOSUserBundle:Group:list }
    requirements:
        _method: GET

fos_user_group_new:
    pattern: /nouveau
    defaults : { _controller :FOSUserBundle:Group:new }

fos_user_group_show:
    pattern: /{groupName}
    defaults : { _controller :FOSUserBundle:Group:show }
    requirements:
        _method: GET

fos_user_group_edit:
    pattern: /{groupName}/editer
    defaults : { _controller :FOSUserBundle:Group:show }

fos_user_group_delete:
    pattern: /{groupName}/supprimer
    defaults : { _controller :FOSUserBundle:Group:delet }
    requirements:
        _method: GET