Projet_accueil:
    path:  /
    defaults: { _controller: ProjetReseauBundle:Reseau:index }

Projet_service:
    path:  /service
    defaults: { _controller: ProjetReseauBundle:Reseau:service }

Projet_reseauGlobal:
    path:  /service/reseau/
    defaults: { _controller: ProjetReseauBundle:Reseau:reseauGlobal }

Projet_reseauSalleView:
    path:  /service/reseau/{salle}
    defaults: { _controller: ProjetReseauBundle:Reseau:reseauSalleView }

Projet_admin:
    path:  /administration
    defaults: { _controller: ProjetReseauBundle:Reseau:index }

Projet_adminSalle:
    path:  /administration/salle
    defaults: { _controller: ProjetReseauBundle:Reseau:formSalle }

Projet_adminApplication:
    path:  /administration/application
    defaults: { _controller: ProjetReseauBundle:Reseau:formApplication }

Projet_adminOrdinateur:
    path:  /administration/ordinateur
    defaults: { _controller: ProjetReseauBundle:Reseau:formOrdinateur }

Projet_adminEtudiant:
    path:  /administration/etudiant
    defaults: { _controller: ProjetReseauBundle:Reseau:formEtudiant }