<?php

namespace Projet\ReseauBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigSalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigSalleRepository extends EntityRepository
{
}
