<?php

namespace Projet\ReseauBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigPostRepository extends EntityRepository
{
}
