<?php

namespace Projet\ReseauBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleRepository extends EntityRepository
{



public function findOneByNom($salle)
{
  // On utilise le QueryBuilder créé par le repository directement pour gagner du temps
  // Plus besoin de faire le select() ni le from() par la suite donc

  $qb = $this->createQueryBuilder('s');

  $qb->where('s.nom = :salle')
      ->setParameter('salle', $salle);


  return $qb->getQuery()
            ->getSingleResult();
}
}